### ISSUE TITLE
feature - Parent actions on Table like expanbd or edit

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#489]
**Is your feature request related to a problem? Please describe.**

a way to expand the tbale or create an edit event form thre parent of the table

**Comment by israelComrax** [comment]
add and expand theres a option with viewChild
edit is not a good idea because we need to add to the table the row and it makes no sense

**Comment by israelComrax** [comment]
close if you agree

**Comment by dvir-comrax** [comment]
i have a table that start on edit state - how i will do that ?

**Comment by israelComrax** [comment]
it also can work with viewChild.
the function addRowGroup(obj: any) is the one you need and you need to pass the row data
