### ISSUE TITLE
inline Navigation logic

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#491]
**Is your feature request related to a problem? Please describe.**
add an inlineNavigation button type. when clicked will navigate to diffrent route

**Comment by israelComrax** [comment]
i dont understand where

**Comment by dvir-comrax** [comment]
in RowActionModel, like inlineEdit and inlineDelete

**Comment by israelComrax** [comment]
added. please check if i did correct

**Comment by dvir-comrax** [comment]
works fine!
