### ISSUE TITLE
stepper layout navigation

### ISSUE THREAD

**Issue by Alex-Shvetsov-Comrax** [ComraxLTD/kakal-ui#554]
**Describe the bug**
while using kkl-steps-layout with a router-outlet inside one of the modules it throws an error after navigating from the router outlet component to the next step

**To Reproduce**
1. Go to 'http://localhost:4200/reservation/parts/transportation'
2. Click on the first or last step
3. see the error "Cannot match any routes. URL Segment: 'reservation/parts/details"

**Expected behavior**
it should give me the option to navigate manually or fix it in the library

**Comment by israelComrax** [comment]
fixed. gets an option input baseUrl that says from what base to navigate to use in cases of nested routing
