### ISSUE TITLE
table mobile mode

### ISSUE THREAD

**Issue by Alex-Shvetsov-Comrax** [ComraxLTD/kakal-ui#555]
**Describe the bug**
while the table have no data in mobile mode it shows only the pagination

**To Reproduce**
1. Go to any page with a table without data ex:"http://localhost:4200/reservation/parts/musical-entertainment"
2. switch to mobile mode
3. See the troubling ui

**Expected behavior**
show a the table headlines or remove the paging

**Screenshots**
![image](https://user-images.githubusercontent.com/87078596/167348665-a8715482-2f7d-4457-86b8-905086905053.png)

**Comment by Alex-Shvetsov-Comrax** [comment]
consider removing paging altogether when its unnecessary

**Comment by israelComrax** [comment]
i cannot remove it since its not controlled by me
