### ISSUE TITLE
accordion stepper layout

### ISSUE THREAD

**Issue by Alex-Shvetsov-Comrax** [ComraxLTD/kakal-ui#557]
**Describe the bug**
the switch between vertical stepper and accordion stepper doesn't work on mobile

**To Reproduce**
1. Go to /reservation/details in education-layput
2. Click on middleNext until it suppose to switch to accordion mode
3. See error

**Expected behavior**
it should work as it works on desktop mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/87078596/167369762-2cdd98a1-5909-4789-9e1c-1e2a2b664124.png)
**Additional context**

**Comment by israelComrax** [comment]
thanks fixed.
