### ISSUE TITLE
kkl-stepper-mobile

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#558]
**Describe the bug**
kkl-stepper-mobile  the main div that contain the arrow, the arrow style is space-between instead of center.

**To Reproduce**
open steps-layout on mobile

**Expected behavior**

**Screenshots**

now
![image](https://user-images.githubusercontent.com/86002958/167371523-3a74c584-04b9-4c54-86dd-6328926348c9.png)

centered

![image](https://user-images.githubusercontent.com/86002958/167371849-936eb115-6f79-4625-9332-3cfde5b6c903.png)

**Comment by israelComrax** [comment]
fixed. its not a bug
