### ISSUE TITLE
kkl-table, text and icon style

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#559]
**Describe the bug**
icon in table cell is not align with text

**To Reproduce**
1. create TableBase instance with colIcon

**Expected behavior**
icon and text will be align, icon need to on left and primary color

**Screenshots**

project

![image](https://user-images.githubusercontent.com/86002958/167384308-aa7785cd-d5dc-4d34-90b9-6c09e1908120.png)

xd

![image](https://user-images.githubusercontent.com/86002958/167384370-323a85d1-b285-44e8-9fe5-bb4b559f6c80.png)

**Comment by israelComrax** [comment]
done
