### ISSUE TITLE
More Infornation on NavbarBottom getNext, getSave methods

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#562]
**Is your feature request related to a problem? Please describe.**

in the cuurent state, since each method return void there is no way to know the current step i am trieng to navigate from.

1. to navigate properly i think each method should emit the current stpes state.
2. also it will be haplful if will implay a filter method to the obs so it will fire only is the step we want.

**Comment by israelComrax** [comment]
its a outside component so it dose not have that info
