### ISSUE TITLE
kkl-tabs hedaers are not stratch

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#568]
Nee to add   mat-stretch-tabs  directive to kklmat-tab-group om kkl-tabs

with

![image](https://user-images.githubusercontent.com/86002958/167800533-d60793d1-5d2d-433f-a6d7-8f5218525e68.png)

without

![image](https://user-images.githubusercontent.com/86002958/167800639-55656a7c-3fd0-4151-b875-3a54de573402.png)

**Comment by israelComrax** [comment]
thanks. fixed
