### ISSUE TITLE
table view in tablet mode

### ISSUE THREAD

**Issue by Alex-Shvetsov-Comrax** [ComraxLTD/kakal-ui#569]
**Describe the bug**
the arrow filter go under the header text in the header cell

**To Reproduce**
1. [Go to '...'](https://calm-grass-040c9920f.1.azurestaticapps.net/reservation/details)
2.f12 go to tablet mode
3. See error

**Expected behavior**
the arrow filter should stay in the same line with the text

**Screenshots**
![image](https://user-images.githubusercontent.com/87078596/167801547-ce8eeb25-4a2f-4f42-ab38-356aa6805fc1.png)

**Additional context**
if impossible consider switching to cards in tablet (check with natali/anat)

**Comment by israelComrax** [comment]
done.
