### ISSUE TITLE
navbar bottom custom buttons

### ISSUE THREAD

**Issue by Alex-Shvetsov-Comrax** [ComraxLTD/kakal-ui#572]
**Describe the bug**
there is no option to add custom buttons to the bottom navbar

**To Reproduce**
1 (https://xd.adobe.com/view/22a28a31-5a9d-44e1-bf62-fec9002bccea-77f1/screen/69898e43-2934-4e27-9f4c-bcb362759169)

**Expected behavior**
there should be a way to inject a template from everywhere in the application with custom buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/87078596/167836201-da84d694-392f-40b2-9c15-93d9a83ba485.png).

**Additional context**

**Comment by israelComrax** [comment]
fixed. added a service to change the text on the buttons. adding template would be only in next version

**Comment by dvir-comrax** [comment]
added
