### ISSUE TITLE
kkl-navigation

### ISSUE THREAD

**Issue by Alex-Shvetsov-Comrax** [ComraxLTD/kakal-ui#575]
**Describe the bug**
the regular steps appear even when a template is provided, and the original steps appear only after the first arrow click

**To Reproduce**
1. /availability-check/search/results
2. uncommet the kkl-navigation tag in the html file 
3. See error

**Expected behavior**
when i provide  a template the original steps shouldn't appear at all otherwise it should show the steps when the component loads

**Screenshots**
![image](https://user-images.githubusercontent.com/87078596/167858777-09e4026c-400e-4938-a2d7-01d981368249.png)
![image](https://user-images.githubusercontent.com/87078596/167859930-e2835e50-92f0-41b1-b5d6-4f4e7121dfb7.png)

**Additional context**
a simple *ngif should suffice, and a behaviorSubject instead of the subject will fix the original steps appearing from the get go

**Comment by israelComrax** [comment]
its out of the library now, dont use this!!!!. consider using carcusl or mobile-stepper.

**Comment by Alex-Shvetsov-Comrax** [comment]
both of those components doesn't support the full functionality or styling of the kkl-navigation, I will ask anat about it

**Comment by dvir-comrax** [comment]
fixed
