### ISSUE TITLE
stepper layout navigation

### ISSUE THREAD

**Issue by Alex-Shvetsov-Comrax** [ComraxLTD/kakal-ui#576]
**Describe the bug**
in the stepper layout when using a router inside the component of one of the steps it fails to continue the routing.
it tries to navigate by adding the path of the step to the current route minus the last child, when using a router-outlet within the step it fails because of the extra path in the url
**To Reproduce**
1. (https://calm-grass-040c9920f.1.azurestaticapps.net/reservation/parts)
2. click on any of the items in the carousel
3. try navigating by clicking on one of the other steps

**Expected behavior**
it should navigate to next step by removing the extra path of the inside router

**Comment by israelComrax** [comment]
fixed from the version tomow
