### ISSUE TITLE
kkl-stepper-mobile  - not update after next event

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#582]
**Describe the bug**
the ui of the steps is not updet when navigate from  navbr-boton next-button

**To Reproduce**
1. create steps-layout
2. change to mobie ui
3. subscribe to  next event from StepsLayoutService 
4. write navigation
5. click on next button

**Possible Solution**
works with kkl-navigaition - i padd an input of stepsSelectionEvent

**Comment by israelComrax** [comment]
looking ok to me. please check again and replay if still happens

**Comment by dvir-comrax** [comment]
עובד
