### ISSUE TITLE
Footer location inside stepper layout

### ISSUE THREAD

**Issue by RamComrax** [ComraxLTD/kakal-ui#610]
**Describe the bug**
The footer in the stepper layout stretches over the whole width of the screen instead of just the width of the content side (not the drawer side to the left). 
When the drawer is open, the footer appears only on the drawer side and not on the content side.
In mobile view, the footer also appears when the drawer is open.

**To Reproduce**
1. Go to https://calm-grass-040c9920f.1.azurestaticapps.net/availability-check/search/results (Education project).
2. open the drawer on the left.
3. change screen view to mobile and repeat 

**Expected behavior**
In the stepper layout, The footer should appear only on the content (right) side, weather the drawer is open or not.. 

**Screenshots**
![stepper-layout-footer](https://user-images.githubusercontent.com/97685690/168968565-a469004d-54a6-4e4c-a84c-bcac51bff26e.png)

**Comment by dvir-comrax** [comment]
fixed
