### ISSUE TITLE
vertical stepper 

### ISSUE THREAD

**Issue by Alex-Shvetsov-Comrax** [ComraxLTD/kakal-ui#618]
**Describe the bug**
in kkl-accordion-steps-layout when clicking on the vertical stepper steps the step changes but the headline stays

**To Reproduce**
1. [Go to '...'](https://calm-grass-040c9920f.1.azurestaticapps.net/reservation/details)
2. Click on a different step in the vertical stepper
3. see that the step changed but the headline stayed 

**Expected behavior**
the step and the headline should correspond

**Screenshots**
![image](https://user-images.githubusercontent.com/87078596/169031937-764ba45d-db23-44dc-9637-c72cb0a8d928.png)

**Additional context**
the stepper works fine when using the middleNext button

**Comment by dvir-comrax** [comment]
fixed
