### ISSUE TITLE
kkl-table - a column with currency symbol

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#631]
**Is your feature request related to a problem? Please describe.**
a way to add a currency symbol to cell text

**Screenshot**
![image](https://user-images.githubusercontent.com/86002958/169279123-e6665f34-bf26-4ee4-a622-4d5b55beef0b.png)

**Comment by israelComrax** [comment]
its working already. just add the it in the currency way like {sum: number, currency: string | symbol}
