### ISSUE TITLE
kkl-ngx-table - a way to access the data object in every column

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#668]
**Is your feature request related to a problem? Please describe.**
i have a ui which one of the column is depaneded on logic of other column.
i need to color the text accordion to the status of the action

**Screenshot**
![image](https://user-images.githubusercontent.com/86002958/169972753-f62d45af-3a5d-4dba-9a09-ca54ef3af7f5.png)

**Describe alternatives you've considered**
in kkl-table-cell, in the cellTemplate section, row as context addistion to the data context

![image](https://user-images.githubusercontent.com/86002958/169973081-b1241381-6680-46d7-9075-1d4300535893.png)

**Comment by israelComrax** [comment]
theres the row everywhere.
please show me where and what you mean

**Comment by israelComrax** [comment]
same as 704
