### ISSUE TITLE
kkl-steps-accordion-layout - override auto navigation

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#691]
**Is your feature request related to a problem? Please describe.**
since there is logic in the kkl-steps-accordion-layout which implment **listenToNextMiddle()**  and self navigation logic it is not possible to ovrride the navigation 

**Describe the solution you'd like**
To override auto navigation logic when desired

**To Reproduce**
1. crreate kkl-steps-accordion-layout 
2. add selectedIndex input
3. subscribe to listenToNextMiddle() and update selectedIndex

**Comment by israelComrax** [comment]
i dont think its needed. theres a stepChanged event and selectedIndex to do it.
listenToNextMiddle is really only for the component to use

**Comment by israelComrax** [comment]
please close if you agree

**Comment by dvir-comrax** [comment]
i try to override and couldn't do it unless i deleted the inner navigation logic @israelComrax

**Comment by israelComrax** [comment]
the problem they have is also with the side buttons. not only the next middle.
but anyway i added the input autoButtons and logic for it.
