### ISSUE TITLE
ngx-datatable - add rowIndex ver

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#695]
I think it will be usfuel to add the rowIndex varibale

![image](https://user-images.githubusercontent.com/86002958/171357147-d557564c-3247-4c42-a145-bddac8c5aaa4.png)

**Comment by israelComrax** [comment]
i added for extra flexibility.
but i dont really thing its good to relay on it in most cases because of sorting filtering adding and etc
