### ISSUE TITLE
fix ngx-tbale - every row color on edit-eaxpnd logic

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#697]
**Describe the bug**
The color is implment on evert expnad event, not only for the edit

**To Reproduce**
1. Go to demo  - Edir tow exapnd
2. create exoand button and click

**Expected behavior**
only edit expand will color the row

**Screenshots**
![image](https://user-images.githubusercontent.com/86002958/171392112-1ed7b2c1-47ac-43dc-8682-003e310152b7.png)

**Comment by israelComrax** [comment]
i see the error. i need to handle it better. will solve tomorrow

**Comment by israelComrax** [comment]
i fixed the example in the demo
