### ISSUE TITLE
kkl-table-cell  - pass all row insted of only data

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#704]
**Is your feature request related to a problem? Please describe.**
i have an ui with the cellTemaplte required data from the row object

**Describe the solution you'd like**
for the kkl-table-cell template pass  also row and column in the context

**Current**
![image](https://user-images.githubusercontent.com/86002958/171612860-9335c148-d541-4919-b9f3-548c922f29e3.png)

**Solution**

![image](https://user-images.githubusercontent.com/86002958/171612955-97677606-2ce4-4274-b7f8-b209a71fd99b.png)

**Comment by israelComrax** [comment]
fixed
