### ISSUE TITLE
kkl-ngx-table - missing borders in not expand table

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#705]
demo

![image](https://user-images.githubusercontent.com/86002958/171617142-fa544059-1ed3-4a8f-ab64-985722c106c0.png)

xd

![image](https://user-images.githubusercontent.com/86002958/171617112-a7cec188-f3a2-4902-be39-8cef00bde813.png)

**Comment by israelComrax** [comment]
fixed
