### ISSUE TITLE
kkl-ngx-table - tablet > mat-card

### ISSUE THREAD

**Issue by dvir-comrax** [ComraxLTD/kakal-ui#715]
**Describe the bug**
mat-card scss affects all mat-cards under table

**To Reproduce**
1. copy ngx-table ui + style
2. render a mat-card as cellTemplate ex card-user
3. set size screen to tablet 

**Expected behavior**
table style will only effect on table comps

**Screenshots**
![image](https://user-images.githubusercontent.com/86002958/172331940-e57f2924-27ae-4035-932c-3bb086eccdcc.png)

**Comment by RamComrax** [comment]
I have checked the issue and you are right, the css selector affects all ```mat-card``` components and not only those intended.
I have added a 'card' class to the intended ```mat-card``` and changed the selector in .scss files from ```mat-card``` to ```.card``` in all the ngx table components in the demo and in kaka-ui as well.

**Comment by israelComrax** [comment]
fixed in demo and kakal-ui. so you can copy
